language: go

go:
  - tip
  - "1.15"
  - "1.14"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - go build

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
