name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      — master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['tip', '1.15', '1.14']
    name: Test with Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: |
          make build cover
          bash <(curl -s https://codecov.io/bash)
